# FoodieDiary

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'SDWebImage'
pod 'FirebaseUI/Storage'

target 'FoodieDiary' do
end
